# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Enjoy programming
email: abramov.andrii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just posting...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abrasha.xyz/" # the base hostname & protocol for your site
twitter_username: abramov_andrii
stackoverflow_link: https://stackoverflow.com/users/5091346/andrii-abramov
github_username: aaabramov

# Build settings
markdown: kramdown
